apiVersion: v1
kind: Service
metadata:
  name: ecomrest-backend
  labels:
    app: ecomrest-backend
spec:
  type: ClusterIP
  selector:
    app: ecomrest-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
