apiVersion: v1
kind: Service
metadata:
  name: ecomrest-client
  labels:
    app: ecomrest-client
spec:
  type: ClusterIP
  selector:
    app: ecomrest-client
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
